############################################
# CORE DEVICE CONFIGURATION
############################################
esphome:
  name: hvac-solarheater
  friendly_name: HVAC-SolarHeater

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable serial logging
logger:

# Enable Home Assistant native API (with encryption)
api:
  encryption:
    key: "KEY"

# OTA updates via ESPHome Dashboard
ota:
  - platform: esphome
    password: "PASS"

############################################
# NETWORKING
############################################
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    gateway: 192.168.100.1
    subnet: 255.255.255.0
    static_ip: 192.168.100.125

  ap:
    ssid: "Hvac-Solarheater"
    password: "PASS"

web_server:
  port: 80

captive_portal:

############################################
# TIME
############################################
time:
  - platform: homeassistant
    id: esptime
    on_time:
      - seconds: 0
        minutes: 0
        hours: 0
        days_of_week: MON-SUN
        then:
          - lambda: |-
              // Optional: Reset a daily counter here if needed
              // id(daily_energy_sensor).reset();

############################################
# BUS CONFIGURATION
############################################
spi:
  clk_pin: GPIO1
  miso_pin: GPIO3

one_wire:
  - platform: gpio
    pin: GPIO2

############################################
# GLOBAL VARIABLES
############################################
globals:
  - id: display_mode
    type: int
    restore_value: no
    initial_value: '0'

  - id: page_number
    type: int
    restore_value: no
    initial_value: '0'

  - id: compressor_runtime
    type: int
    restore_value: no
    initial_value: "0"

  - id: pwm_level
    type: float
    initial_value: '0.0'

  # Error state: 0 = OK, 1 = Flow Low, 2 = Flow High (warn), 3 = Overheat, 4 = Sensor/Flow fault
  - id: error_state
    type: int
    restore_value: no
    initial_value: '0'

  # Used for auto-recovery after stable operation
  - id: error_clear_timer
    type: int
    restore_value: no
    initial_value: '0'

  # Smoothed flow values
  - id: avg_flow_hot
    type: float
    restore_value: no
    initial_value: "0.0"

  - id: avg_flow_cold
    type: float
    restore_value: no
    initial_value: "0.0"

  # Compressor on-time (millis at last start)
  - id: compressor_on_time
    type: int
    restore_value: no
    initial_value: "0"

############################################
# SENSORS
############################################
sensor:

  # MAX6675 thermocouples
  - platform: max6675
    name: "Tank Temperature Backup"
    id: tank_temp2
    cs_pin: GPIO18
    update_interval: 30s
    filters:
      - offset: 2

  - platform: max6675
    name: "Solar Collector Temperature"
    id: collector_temp
    cs_pin: GPIO22
    update_interval: 10s
    filters:
      - offset: -10

  # Dallas one-wire sensors
  - platform: dallas_temp
    id: cold
    address: 0xaa0306979462f828
    update_interval: 10s
    name: "Cold HVAC Out"
    icon: mdi:snowflake-thermometer

  - platform: dallas_temp
    id: coldin
    address: 0x7a031497944f2428
    update_interval: 10s
    name: "Cold HVAC In"
    icon: mdi:snowflake-melt
    filters:
      - offset: -0.2

  - platform: dallas_temp
    id: hot
    address: 0xda03019794413928
    update_interval: 10s
    name: "Hot HVAC Out"

  - platform: dallas_temp
    id: hotin
    address: 0x9e031497940df928
    update_interval: 10s
    name: "Hot HVAC In"
    filters:
      - offset: 2.7

  - platform: dallas_temp
    id: motortemp
    address: 0x0e031097945b6728
    update_interval: 10s
    name: "Compressor Temperature"

  - platform: dallas_temp
    id: tanktemp
    address: 0x12031497944b7728
    update_interval: 30s
    name: "Storage Tank Temperature"

# Flow sensors
  - platform: pulse_counter
    id: flowhot
    pin: GPIO36
    name: "HVAC Hot Water flow"
    update_interval: 10s
    filters:
      - debounce: 0.1s
      - round: 1
      # PREVIOUS: return ((x / 20.0) * 60.0) * 0.58;
      # NEW: Divide by 1000 to convert mL to Liters
      - lambda: return (((x / 20.0) * 60.0) * 0.58) / 1000.0; 
    unit_of_measurement: "L/min"
    accuracy_decimals: 2  # Added to see decimals like 8.55

  - platform: pulse_counter
    id: flowcold
    pin: GPIO39
    name: "HVAC Cold Water flow"
    update_interval: 5s
    filters:
      - debounce: 0.1s
      - round: 1
      # PREVIOUS: return (x / 20.0) * 60.0;
      # NEW: Divide by 1000 to convert mL to Liters
      - lambda: return ((x / 20.0) * 60.0) / 1000.0;
    unit_of_measurement: "L/min"
    accuracy_decimals: 2

  # ----------------------------------------
  # POWER & ENERGY CALCULATIONS
  # ----------------------------------------
  
  # 1. Instantaneous Thermal Power (Watts)
  - platform: template
    name: "HVAC Thermal Power Output"
    id: thermal_power_watts
    unit_of_measurement: "W"
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      if (!id(compressor).state) return 0.0;
      
      float flow = id(flowhot).state;
      float dt = id(hot).state - id(hotin).state;
      
      if (isnan(flow) || isnan(dt) || flow < 1.0) return 0.0;
      
      // Constant: 4186 J/kgK / 60s = 69.77
      return flow * dt * 69.77;

  # 2. Total Energy Accumulator (Wh)
  - platform: integration
    sensor: thermal_power_watts
    name: "Power Output Total"
    id: thermal_energy_total
    unit_of_measurement: "Wh"
    time_unit: h
    integration_method: left # Corrected parameter
    restore: true

  # Compressor electrical energy estimate
  - platform: template
    name: "HVAC Power Consumption"
    id: compressor_power_consumption
    update_interval: 5s
    accuracy_decimals: 2
    unit_of_measurement: "Wh"
    lambda: |-
      if (!id(compressor).state) {
        return 0.0f;
      }
      int compressor_runtime_value = id(compressor_runtime);
      float compressor_runtime_hours = compressor_runtime_value / 3600.0f;
      return 1300.0f * compressor_runtime_hours;

  - platform: wifi_signal
    name: WiFi Strength
    id: wifi_stats
    update_interval: 60s

############################################
# OUTPUTS
############################################
output:
  - platform: ledc
    id: pwm_pump
    pin: GPIO0
    frequency: "1500 Hz"
    min_power: 0%
    max_power: 100%

  # Local alarm LED
  - platform: gpio
    id: alarm_led
    pin: GPIO23

############################################
# SWITCHES
############################################
switch:
  - platform: gpio
    pin: GPIO17
    inverted: False
    id: dallas_temppower
    icon: "mdi:restart"
    restore_mode: RESTORE_DEFAULT_ON

  - platform: gpio
    pin: GPIO25
    inverted: False
    id: compressor
    name: "HVAC Compressor"
    icon: "mdi:restart"
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "Compressor turned on"
      - switch.turn_on: pumpcold
      - switch.turn_on: pumphot
    on_turn_off:
      - switch.turn_on: pumpcold
      - logger.log: "Compressor just turned off"

  - platform: gpio
    pin: GPIO14
    inverted: False
    id: pumphot
    name: "Pump Hot side"
    icon: mdi:fire
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "Water Pump hot side just turned on"
    on_turn_off:
      - logger.log: "Water Pump hot side just turned off"

  - platform: gpio
    pin: GPIO27
    inverted: False
    id: pumpcold
    name: "Pump Cold side"
    icon: mdi:snowflake
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "Water Pump cold side just turned on"
    on_turn_off:
      - logger.log: "Water Pump cold side just turned off"

  - platform: gpio
    pin: GPIO4
    inverted: True
    id: compressorcool
    icon: mdi:valve
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "Compressor too hot"
    on_turn_off:
      - logger.log: "Compressor normal"

  - platform: restart
    name: Device Restart

############################################
# NUMBERS
############################################
number:
  - platform: template
    name: "Solar Heater Setpoint"
    id: tank_temp_setpoint
    min_value: 30
    max_value: 70
    step: 1.0
    initial_value: 55
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    optimistic: true

############################################
# TEXT SENSORS
############################################
text_sensor:
  - platform: template
    name: "Function"
    id: function
    icon: mdi:function-variant

  # Updated to just display the new calculated values nicely
  - platform: template
    name: "Power output"
    id: powerout
    lambda: |-
      return {to_string(id(thermal_power_watts).state) + " W"};
    update_interval: 5s

  - platform: template
    name: "System Status"
    id: system_status

  - platform: template
    name: "System Status JSON"
    id: system_status_json

  - platform: template
    name: "Last Error"
    id: last_error

  - platform: template
    name: "Solar Pump Speed"
    id: pump_speed
    lambda: |-
      int percentage = static_cast<int>(id(pwm_level) * 100.0f);
      return {to_string(percentage) + "%"};
    update_interval: 1s

############################################
# INTERVAL LOGIC
############################################
interval:

  # 30s – solar pump modulation
  - interval: 30s
    then:
      - if:
          condition:
            and:
              - lambda: 'return id(collector_temp).state < 120.0f;'
              - lambda: 'return id(collector_temp).state > id(tanktemp).state;'
              - lambda: 'return id(tanktemp).state < id(tank_temp_setpoint).state;'
          then:
            - lambda: |-
                float temp_diff = id(collector_temp).state - id(tanktemp).state;
                float pwm_percentage = temp_diff / 10.0f;
                if (pwm_percentage < 0.0f) pwm_percentage = 0.0f;
                if (pwm_percentage > 1.0f) pwm_percentage = 1.0f;
                id(pwm_pump).set_level(pwm_percentage);
                id(pwm_level) = pwm_percentage;
          else:
            - output.turn_off: pwm_pump
            - lambda: 'id(pwm_level) = 0.0f;'

  # 10s – Safety & Monitoring (Cleaned up)
  - interval: 10s
    then:
      # 1) Flow averaging and idle status
      - lambda: |-
          float flow_hot = id(flowhot).state;
          float flow_cold = id(flowcold).state;
          const float alpha = 1.0f;

          id(avg_flow_hot) = alpha * id(avg_flow_hot) + (1.0f - alpha) * flow_hot;
          id(avg_flow_cold) = alpha * id(avg_flow_cold) + (1.0f - alpha) * flow_cold;

          if (!id(compressor).state) {
            id(system_status).publish_state("System Idle");
            id(system_status_json).publish_state("{\"severity\":\"info\",\"code\":0,\"message\":\"System Idle\"}");
          }

      # 2) Critical flow too low
      - lambda: |-
          if (!id(compressor).state) return;
          if (id(error_state) != 0) return;

          float avg_hot = id(avg_flow_hot);
          float avg_cold = id(avg_flow_cold);

          if (avg_hot < 1.0f || avg_cold < 1.0f) {
            char msg[160];
            snprintf(msg, sizeof(msg),
                     "Abnormal flow: expected > 1.0 L/min, Hot: %.2f L/min, Cold: %.2f L/min",
                     avg_hot, avg_cold);

            id(error_state) = 1;
            id(error_clear_timer) = 0;

            id(system_status).publish_state(msg);
            id(last_error).publish_state(msg);

            char json[256];
            snprintf(json, sizeof(json),
                     "{\"severity\":\"critical\",\"code\":1,\"message\":\"%s\"}", msg);
            id(system_status_json).publish_state(json);

            id(alarm_led).turn_on();
            id(compressor).turn_off();
            id(pumphot).turn_off();
            id(pumpcold).turn_off();
          }

      # 3) Flow too high warning
      - lambda: |-
          if (!id(compressor).state) return;
          if (id(error_state) != 0) return;

          float avg_hot = id(avg_flow_hot);
          float avg_cold = id(avg_flow_cold);

          if (avg_hot > 25.0f || avg_cold > 25.0f) {
            char msg[160];
            snprintf(msg, sizeof(msg),
                     "Abnormal flow: expected < 25.0 L/min, Hot: %.2f L/min, Cold: %.2f L/min",
                     avg_hot, avg_cold);
            
            id(system_status).publish_state(msg);
            id(last_error).publish_state(msg);
            
            char json[256];
            snprintf(json, sizeof(json),
                     "{\"severity\":\"warning\",\"code\":2,\"message\":\"%s\"}", msg);
            id(system_status_json).publish_state(json);
          }

      # 4) Compressor temperature safety
      - lambda: |-
          if (!id(compressor).state) return;

          float temp = id(motortemp).state;

          if (temp > 99.0f && id(error_state) == 0) {
            const char *msg = "Compressor overheating: OFF";
            id(error_state) = 3;
            id(error_clear_timer) = 0;

            id(system_status).publish_state(msg);
            id(last_error).publish_state(msg);

            char json[256];
            snprintf(json, sizeof(json),
                     "{\"severity\":\"critical\",\"code\":3,\"message\":\"%s\"}", msg);
            id(system_status_json).publish_state(json);

            id(alarm_led).turn_on();
            id(compressor).turn_off();
            id(pumphot).turn_off();
            id(pumpcold).turn_off();
          }

          if (temp > 95.0f) {
            id(compressorcool).turn_on();
          } else if (temp < 90.0f) {
            id(compressorcool).turn_off();
          }

          if (temp < 90.0f && id(error_state) == 0) {
            id(system_status).publish_state("Compressor temperature normal");
            id(system_status_json).publish_state("{\"severity\":\"info\",\"code\":0,\"message\":\"Compressor temperature normal\"}");
          }

      # 5) Compressor runtime
      - lambda: |-
          if (!id(compressor).state) {
            id(compressor_on_time) = 0;
            return;
          }
          if (id(error_state) != 0) return;

          uint32_t now = millis();
          uint32_t start = (uint32_t) id(compressor_on_time);
          if (start == 0u) {
            id(compressor_on_time) = (int) now;
            start = now;
          }
          uint32_t elapsed = now - start;
          if (elapsed < 20000u) {
            id(system_status).publish_state("OK (warm-up)");
            id(system_status_json).publish_state("{\"severity\":\"info\",\"code\":0,\"message\":\"OK (warm-up)\"}");
            return;
          }
          id(compressor_runtime) += 10;

      # 6) Sensor/flow sanity check
      - lambda: |-
          if (!id(compressor).state) return;
          if (id(error_state) != 0) return;

          float delta_hot = id(hot).state - id(hotin).state;
          float delta_cold = id(cold).state - id(coldin).state;
          float flow_hot = id(flowhot).state;
          float flow_cold = id(flowcold).state;

          bool sensors_ok = true;
          if (isnan(delta_hot) || isnan(delta_cold)) sensors_ok = false;
          if (flow_hot < 1.0f || flow_cold < 1.0f) sensors_ok = false;

          if (!sensors_ok) {
            const char *msg = "Fault: Sensor or flow issue";
            id(error_state) = 4;
            id(error_clear_timer) = 0;
            id(system_status).publish_state(msg);
            id(last_error).publish_state(msg);
            char json[256];
            snprintf(json, sizeof(json),
                     "{\"severity\":\"critical\",\"code\":4,\"message\":\"%s\"}", msg);
            id(system_status_json).publish_state(json);
            id(alarm_led).turn_on();
            id(compressor).turn_off();
            id(pumphot).turn_off();
            id(pumpcold).turn_off();
          }

      # 7) Auto-recovery Logic
      - lambda: |-
          if (!id(compressor).state) return;
          if (id(error_state) != 0) {
             // Try to clear error if flow recovers
             if (id(flowhot).state >= 1.0f) {
                id(error_clear_timer) += 1;
                if (id(error_clear_timer) >= 6) {
                   id(error_state) = 0;
                   id(error_clear_timer) = 0;
                   id(alarm_led).turn_off();
                   id(system_status).publish_state("OK");
                   id(system_status_json).publish_state("{\"severity\":\"info\",\"code\":0,\"message\":\"OK\"}");
                }
             } else {
                id(error_clear_timer) = 0;
             }
          } else {
             // Status update if everything is running fine
             id(system_status).publish_state("OK");
             id(system_status_json).publish_state("{\"severity\":\"info\",\"code\":0,\"message\":\"OK\"}");
          }

############################################
# CLIMATE – MAIN HEATING CONTROL
############################################
climate:
  - platform: thermostat
    id: climatehot
    name: "HVAC Heater"
    sensor: tanktemp
    icon: mdi:thermostat

    min_heating_off_time: 60s
    min_heating_run_time: 0s
    min_idle_time: 60s

    heat_action:
      - switch.turn_on: pumpcold
      - delay: 3s
      - switch.turn_on: pumphot
      - delay: 3s
      - switch.turn_on: compressor
      - logger.log: "Heating"
      - text_sensor.template.publish:
          id: function
          state: "Heating"

    idle_action:
      - switch.turn_off: compressor
      - delay: 20s
      - switch.turn_off: pumpcold
      - text_sensor.template.publish:
          id: function
          state: "Idle"
      # - delay: 20min
      # - switch.turn_off: pumphot

    default_preset: Winter
    preset:
      - name: Summer
        default_target_temperature_low: 40 °C
      - name: Winter
        default_target_temperature_low: 50 °C

    visual:
      min_temperature: 30
      max_temperature: 70
      temperature_step: 1

    heat_deadband: 7 °C
    heat_overrun: 0.7 °C
